### PR TITLE
Stage react api

### PR DESCRIPTION
**Pull request by ssbrandt**
Stage 1.1 Markup

### CODE REVIEW

**Comment by FiLLa-FaS** [comment]
Hi! Thank you for sending your project for review, it already looks pretty good! I marked several issues below and hope that they can help you to improve your project and get more points. Good luck!✨

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.
    * Mismatches of the main page on 1440px https://pasteboard.co/qCPauhbz8Okx.png
    * Mismatches of the main page on 768px https://pasteboard.co/ppySVIAjKCWh.png https://pasteboard.co/QVSb3ZAct4wg.png https://pasteboard.co/GcmIEAijrrk5.png
    * Mismatches of the main page on 320px https://pasteboard.co/fpwF9dfjXd4I.png https://pasteboard.co/As6CUXBrYP6E.png https://pasteboard.co/4IweyhbS7g8l.png
    * Modal window shouldn't have empty bottom space on 320 viewport
    * Incorrect location of the `form__redirect` on mobile screen resolutions
    * You should set the text color for the `form__redirect` according to the mockup
    * Mismatches of the `saved-news` page on 768 viewport https://pasteboard.co/EeA3CxzdODVj.png and on 320 viewport https://pasteboard.co/noq5wHiZOf7P.png
    * Mobile nav menu block should have background without the opacity and overlay with different opacity value according to the mockup
- [ ]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
    * All news cards should have equal height https://pasteboard.co/OiXoVLJ7kEds.png
    * All project components should be centered horizontally on all screen resolutions
- [ ]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
    * All links in footer should work properly
- [ ]  Classes are named according to BEM specifications.
    * Please don't use capital letters in class names
    * You can't use BEM elements outside of their blocks, for example `background__image` can't be used outside the `background` block class. Please fix all similar cases **throughout the project**
    * You can't use the BEM modifiers without their base blocks/elements classes, for example `card__select_text` can't be used without the `card__select`. Please fix all similar cases **throughout the project**
    * `footer_item` classes should actually be BEM elements
- [ ]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
    * Please use the `nav` tag for the navigation blocks
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid` layouts are used to arrange elements whenever applicable.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.
    * `card__badge` should have hover and clicked states
    * `form__redirect` should have pointer cursor
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [ ]  Form elements should be highlighted when focused.
    * `form__redirect` should be highlighted when focused
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 49

**Comment by FiLLa-FaS** [comment]
Hi! Thanks for the corrections, your project looks much better! Several small issues below are left. Good luck!✨

# Summary:
### Performance Criteria

- [x]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.
- [ ]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
    * All project components should be centered horizontally on all screen resolutions
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [ ]  Classes are named according to BEM specifications.
    * `mobile-nav` block should contain elements of `mobile-nav` block instead of `nav` or you can create a BEM mix and add there `nav` class
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid` layouts are used to arrange elements whenever applicable.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.
    * `card__badge` should have hover and clicked states
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [ ]  Form elements should be highlighted when focused.
    * `form__redirect` should be visually highlighted when focused
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 79

**Comment by ssbrandt** [comment]
@FiLLa-FaS Thanks for the review. Would it be in scope for you to point out the components that aren't centered horizontally? I've look through the components at various dimensions and am having trouble seeing which ones aren't centered.

**Comment by FiLLa-FaS** [comment]
@ssbrandt I mean the news cards (I remember that there's a trouble with `saved-news` page news cards, but it will be better to also check them on the main page

**Comment by ssbrandt** [comment]
@FiLLa-FaS Thanks, I see the issue now.

**Comment by FiLLa-FaS** [comment]
Hi! You got more than 80 points, so I'm very glad to accept your project this time! You still can fix the rest small issues if you want to improve the project a little more. Good luck on the next stage!🙌🚀

# Summary:
### Performance Criteria

- [x]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.
- [ ]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
    * All project components should be centered horizontally on all screen resolutions (please take a look at news cards for both pages at 769px - 880px screen resolutions
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [x]  Classes are named according to BEM specifications.
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid` layouts are used to arrange elements whenever applicable.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.
    * `card__badge` hover and clicked states don't correspond the mockup
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 85

**Pull request merged**
